language: node_js
env: NPS=pwsh
matrix:
  include:
      # linux 16.04 - pwsh
    - os: linux
      dist: xenial
      sudo: required
      node_js:
        - "lts/*"
        - "lts/boron"
      before_install:
        - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
        - sudo dpkg -i packages-microsoft-prod.deb
        - sudo apt-get update
        - sudo apt-get install -y powershell
      # osx - pwsh
    - os: osx
      node_js:
        - "lts/*"
        - "lts/boron"
      before_install: brew cask install powershell
      # windows - pwsh
    - os: windows
      node_js:
        - "lts/*"
        - "lts/boron"
      before_install: choco install powershell-core
      # windows - powershell
    - os: windows
      env: NPS=powershell
      node_js:
        - "lts/*"
        - "lts/boron"
cache: npm
install:
  - npm install 
  - npm install -g gulp
script:
  # - npm run build
  - npm run test:coveralls