language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
before_install:
  - wget "https://github.com/PowerShell/PowerShell/releases/download/v6.0.0-alpha.16/powershell_6.0.0-alpha.16-1ubuntu1.16.04.1_amd64.deb"
  - sudo dpkg -i powershell_6.0.0-alpha.16-1ubuntu1.16.04.1_amd64.deb
  - sudo apt-get install -f
before_script:
  - npm install -g gulp
script:
  - npm run build
  - npm run test:coveralls
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.npm
