language: node_js
node_js:
  - "lts/*"
  - "lts/boron"
env: NPS=pwsh
matrix:
  include:
      # linux 16.04 - pwsh
    - os: linux
      dist: xenial
      sudo: required
      before_install: sudo dpkg -i powershell_6.1.1-1.ubuntu.16.04_amd64.deb
      install: sudo apt-get install -f
      # osx - pwsh
    - os: osx
      install: brew cask install powershell
      # windows - pwsh
    - os: windows
      install: choco install powershell-core
      # windows - powershell
    - os: windows
      env: NPS=powershell
cache: npm
before_script:
  - npm install 
  - npm install -g gulp
script:
  # - npm run build
  - npm run test:coveralls