language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
before_install:
  - bash < (curl -fsSL https://raw.githubusercontent.com/PowerShell/PowerShell/v6.0.0-alpha.16/tools/download.sh)
before_script:
  - npm install -g gulp
script:
  - npm run build
  - npm run test:coveralls
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.npm
